/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'productId' : string,
  'quantity' : bigint,
  'priceINR' : number,
}
export type ExternalBlob = Uint8Array;
export interface PointsHistory {
  'description' : string,
  'timestamp' : Time,
  'points' : bigint,
}
export interface Product {
  'id' : string,
  'stockQuantity' : bigint,
  'photoUrls' : Array<ExternalBlob>,
  'name' : string,
  'description' : string,
  'category' : string,
  'priceINR' : number,
}
export interface Review {
  'userId' : string,
  'reviewText' : string,
  'productId' : string,
  'timestamp' : Time,
  'rating' : bigint,
}
export interface Reward {
  'id' : string,
  'pointsRequired' : bigint,
  'description' : string,
  'discountPercentage' : number,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SupportRequest {
  'id' : string,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WishlistItem { 'productId' : string, 'addedAt' : Time }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addReview' : ActorMethod<[Review], undefined>,
  'addReward' : ActorMethod<[Reward], undefined>,
  'addSupportRequest' : ActorMethod<[SupportRequest], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getPointsHistory' : ActorMethod<[], Array<PointsHistory>>,
  'getProductById' : ActorMethod<[string], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getReviewsByProduct' : ActorMethod<[string], Array<Review>>,
  'getRewards' : ActorMethod<[], Array<Reward>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSupportRequests' : ActorMethod<[], Array<SupportRequest>>,
  'getUserPoints' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<WishlistItem>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCart' : ActorMethod<[Array<CartItem>], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateWishlist' : ActorMethod<[Array<WishlistItem>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];